# Generated by Django 4.0.1 on 2022-01-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_id', models.IntegerField()),
                ('flavor_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flavor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlavorWine',
            fields=[
                ('flavor_wine_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('flavor_group', models.TextField(blank=True, null=True)),
                ('flavor_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flavor_wine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocalWine',
            fields=[
                ('lw_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lw_name', models.TextField(blank=True, null=True)),
                ('lw_country', models.TextField(blank=True, null=True)),
                ('lw_region', models.TextField(blank=True, null=True)),
                ('lw_year', models.TextField(blank=True, null=True)),
                ('lw_type', models.TextField(blank=True, null=True)),
                ('lw_price', models.TextField(blank=True, null=True)),
                ('lw_alcohol', models.TextField(blank=True, null=True)),
                ('lw_seller', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'local_wine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('wine_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('wine_name', models.TextField(blank=True, null=True)),
                ('wine_type', models.TextField(blank=True, null=True)),
                ('wine_year', models.IntegerField(blank=True, null=True)),
                ('wine_alcohol', models.FloatField(blank=True, null=True)),
                ('wine_country', models.TextField(blank=True, null=True)),
                ('wine_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wine',
                'managed': False,
            },
        ),
    ]
