# Generated by Django 4.0.1 on 2022-01-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorGroup',
            fields=[
                ('group_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('group_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flavor_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlavorWineGroup',
            fields=[
                ('flavor_wine_group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('flavor_wine_group_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flavor_wine_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WineStructure',
            fields=[
                ('wine_structure_id', models.IntegerField(primary_key=True, serialize=False)),
                ('wine_acidity', models.FloatField(blank=True, null=True)),
                ('wine_fizziness', models.FloatField(blank=True, null=True)),
                ('wine_intensity', models.FloatField(blank=True, null=True)),
                ('wine_sweetness', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wine_structure',
                'managed': False,
            },
        ),
    ]
