# Generated by Django 4.0.1 on 2022-01-31 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WineAPI', '0002_flavorgroup_flavorwinegroup_winestructure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.DeleteModel(
            name='FlavorWine',
        ),
    ]
